import React,{useEffect,useMemo,useRef,useState,type ChangeEvent,type TouchEvent} from 'react';
import {createRoot} from 'react-dom/client';
import {registerSW} from 'virtual:pwa-register';
import {deleteDay,getDays,getProgram,getSettings,importProgram,makeBackup,markExport,parseBackup,restoreBackup,saveDay,shareBackup,type Backup} from './storage';
import {emptyDay,hasContent,localDate,toPlanItem,today,type DayEntry,type PlanItem,type ProgramPackage} from './model';
import './style.css';

type Route={page:'calendar'|'program'}|{page:'day';date:string};
const readRoute=():Route=>{const hash=location.hash.slice(1);return /^day\/\d{4}-\d{2}-\d{2}$/.test(hash)?{page:'day',date:hash.slice(4)}:hash==='program'?{page:'program'}:{page:'calendar'}};
const go=(route:Route)=>{location.hash=route.page==='day'?`day/${route.date}`:route.page};
const formatDate=(date:string,options:Intl.DateTimeFormatOptions={day:'numeric',month:'long'})=>new Intl.DateTimeFormat('ru-RU',options).format(localDate(date));
const ratingOptions=Array.from({length:11},(_,index)=>index);
const durationOptions=Array.from({length:73},(_,index)=>index*5);
function NumberField({label,value,onChange,options}:{label:string;value:number|null;onChange:(value:number|null)=>void;options:number[]}){
  const values=value!==null&&!options.includes(value)?[...options,value].sort((a,b)=>a-b):options;
  return <label className="field"><span>{label}</span><select value={value??''} onChange={event=>onChange(event.target.value===''?null:Number(event.target.value))}><option value="">Не записано</option>{values.map(option=><option key={option} value={option}>{option}</option>)}</select></label>;
}
function Note({label,value,onChange,placeholder,rows=5}:{label:string;value:string;onChange:(value:string)=>void;placeholder?:string;rows?:number}){return <label className="field"><span>{label}</span><textarea value={value} rows={rows} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/></label>}
function PanelTitle({number,title}:{number:string;title:string}){return <div className="panel-title"><span>{number}</span><h2>{title}</h2></div>}

function Calendar({days,month,onMonthChange,onOpen}:{days:DayEntry[];month:Date;onMonthChange:(month:Date)=>void;onOpen:(date:string)=>void}){
  const entries=useMemo(()=>new Map(days.filter(hasContent).map(day=>[day.date,day])),[days]);
  const first=new Date(month.getFullYear(),month.getMonth(),1),offset=(first.getDay()+6)%7,start=new Date(first);start.setDate(first.getDate()-offset);
  const cells=Array.from({length:42},(_,index)=>{const date=new Date(start);date.setDate(start.getDate()+index);return {date:today(date),day:date.getDate(),inside:date.getMonth()===month.getMonth()}});
  const move=(step:number)=>onMonthChange(new Date(month.getFullYear(),month.getMonth()+step,1));
  return <main className="content calendar-page"><div className="page-intro"><span className="eyebrow">ДНЕВНИК ТРЕНИРОВОК</span><h1>Календарь</h1><p>Нажми на день, чтобы записать тренировку или изменить прошлую запись.</p></div>
    <section className="panel calendar-panel"><div className="calendar-top"><div><span className="eyebrow">ВЫБЕРИ ДЕНЬ</span><h2>{new Intl.DateTimeFormat('ru-RU',{month:'long',year:'numeric'}).format(month)}</h2></div><div className="calendar-controls"><button className="ghost" onClick={()=>onMonthChange(localDate(today()))}>Сегодня</button><button className="icon-button" aria-label="Предыдущий месяц" onClick={()=>move(-1)}>‹</button><button className="icon-button" aria-label="Следующий месяц" onClick={()=>move(1)}>›</button></div></div>
      <div className="calendar-grid weekdays">{['Пн','Вт','Ср','Чт','Пт','Сб','Вс'].map(name=><span key={name}>{name}</span>)}</div>
      <div className="calendar-grid dates">{cells.map(cell=>{const entry=entries.get(cell.date),marked=!!entry;return <button key={cell.date} className={`date-cell ${cell.inside?'':'outside'} ${cell.date===today()?'today':''} ${marked?'recorded':''}`} onClick={()=>onOpen(cell.date)} aria-label={`${formatDate(cell.date)}, ${marked?'есть запись':'записи нет'}`}><span>{cell.day}</span>{marked&&<i className={entry?.climbing.trim()||entry?.conditioning.trim()?'fact-dot':'plan-dot'}/>}</button>})}</div>
      <p className="calendar-hint"><i className="fact-dot"/> Запись в этот день <span>·</span> Пустой день не считается пропуском</p>
    </section>
  </main>;
}

function PlanList({items}:{items:PlanItem[]}){if(!items.length)return null;return <div className="plan-list"><div className="small-heading">ПЛАН ИЗ ПРОГРАММЫ</div>{items.map(item=><details className="plan-item" key={item.id}><summary><strong>{item.title}</strong><span>{item.dose||'Без дозировки'}</span></summary>{item.instruction&&<p>{item.instruction}</p>}</details>)}</div>}

function DayPage({date,stored,program,onBack,onProgram,onSaved,onDeleted}:{date:string;stored:DayEntry|undefined;program:ProgramPackage|null;onBack:()=>void;onProgram:()=>void;onSaved:(day:DayEntry)=>void;onDeleted:(date:string)=>void}){
  const initial=stored||emptyDay(date),[draft,setDraft]=useState(initial),[saveState,setSaveState]=useState<'saved'|'saving'|'error'>('saved'),[error,setError]=useState('');
  const current=useRef(initial),revision=useRef(initial.revision),timer=useRef<ReturnType<typeof setTimeout>|null>(null),queue=useRef(Promise.resolve()),sequence=useRef(0),dirty=useRef(false),failed=useRef(false),removed=useRef(false),swipe=useRef<{x:number;y:number}|null>(null);
  useEffect(()=>{const hidden=()=>{if(document.visibilityState==='hidden')void flush()};document.addEventListener('visibilitychange',hidden);return()=>{document.removeEventListener('visibilitychange',hidden);if(timer.current)clearTimeout(timer.current);if(dirty.current&&!removed.current)void flush()}},[]);
  function flush(){if(timer.current){clearTimeout(timer.current);timer.current=null}if(!dirty.current||removed.current)return queue.current;const snapshot=structuredClone(current.current),ticket=sequence.current;setSaveState('saving');queue.current=queue.current.then(async()=>{const saved=await saveDay(snapshot,revision.current);revision.current=saved.revision;onSaved(saved);if(sequence.current===ticket){current.current=saved;setDraft(saved);dirty.current=false;failed.current=false;setSaveState('saved')}}).catch(cause=>{failed.current=true;setError(cause instanceof Error?cause.message:String(cause));setSaveState('error')});return queue.current}
  function patch(change:Partial<DayEntry>,immediate=false){const next={...current.current,...change};current.current=next;setDraft(next);dirty.current=true;sequence.current++;setSaveState('saving');if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>void flush(),immediate?0:300)}
  async function leave(destination:'calendar'|'program'='calendar'){await flush();if(failed.current)return;destination==='program'?onProgram():onBack()}
  async function remove(){if(!confirm('Удалить запись за этот день?'))return;if(timer.current)clearTimeout(timer.current);dirty.current=false;removed.current=true;await queue.current;try{await deleteDay(date,revision.current);onDeleted(date)}catch(cause){removed.current=false;setError(cause instanceof Error?cause.message:String(cause));setSaveState('error')}}
  function touchStart(event:TouchEvent<HTMLElement>){if((event.target as Element).closest('input,textarea,select')){swipe.current=null;return}swipe.current={x:event.touches[0].clientX,y:event.touches[0].clientY}}
  function touchEnd(event:TouchEvent<HTMLElement>){if(!swipe.current)return;const dx=event.changedTouches[0].clientX-swipe.current.x,dy=event.changedTouches[0].clientY-swipe.current.y;swipe.current=null;if(dx>90&&Math.abs(dy)<70)void leave()}
  const template=program?.templates.find(item=>item.id===draft.templateId);
  const choices=template?.exerciseIds.map(id=>program?.exercises.find(item=>item.id===id)).filter((item):item is NonNullable<typeof item>=>!!item)||[];
  const climbingPlan=draft.plan.filter(item=>item.kind!=='hang'&&item.kind!=='strength'),strengthPlan=draft.plan.filter(item=>item.kind==='hang'||item.kind==='strength');
  return <main className="content day-page" onTouchStart={touchStart} onTouchEnd={touchEnd} onBlurCapture={()=>{if(timer.current)void flush()}}><div className="day-heading"><button className="back-button" onClick={()=>void leave()}>← К календарю</button><span className={`save-state ${saveState}`}>{saveState==='saved'?'● Сохранено на устройстве':saveState==='saving'?'◌ Сохраняю…':'! Не сохранено'}</span></div>
    {saveState==='error'&&<div className="error-box">{error}<button onClick={()=>void flush()}>Повторить</button></div>}
    <div className="page-intro"><span className="eyebrow">ЗАПИСЬ ЗА ДЕНЬ</span><h1>{formatDate(date,{weekday:'long',day:'numeric',month:'long'})}</h1><p>Можно заполнить только то, что хочется сохранить. Пустые поля останутся пустыми.</p></div>
    <div className="day-layout"><div className="day-main"><section className="panel"><PanelTitle number="01" title="Цель тренировки"/><Note label="Что хочу попробовать" value={draft.goal} onChange={goal=>patch({goal})} placeholder="Необязательно" rows={3}/></section>
      <section className="panel training-panel"><PanelTitle number="02" title="Тренировка"/>{program?<><label className="field"><span>План из программы</span><select value={draft.templateId||''} onChange={event=>{const id=event.target.value||null,selected=program.templates.find(item=>item.id===id);patch({templateId:id,plan:selected?selected.exerciseIds.map(key=>program.exercises.find(exercise=>exercise.id===key)).filter((item):item is NonNullable<typeof item>=>!!item).map(toPlanItem):[]},true)}}><option value="">Без шаблона</option>{program.templates.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>{choices.length>0&&<div className="exercise-filter"><span className="small-heading">ПОКАЗЫВАТЬ В ПЛАНЕ</span>{choices.map(exercise=><label key={exercise.id}><input type="checkbox" checked={draft.plan.some(item=>item.id===exercise.id)} onChange={event=>patch({plan:event.target.checked?[...draft.plan,toPlanItem(exercise)]:draft.plan.filter(item=>item.id!==exercise.id)},true)}/>{exercise.title}</label>)}</div>}</>:<p className="muted">Программа пока не загружена. Можно вести дневник без неё или <button className="inline-link" onClick={()=>void leave('program')}>импортировать программу</button>.</p>}
        <div className="training-fields"><div className={`entry-split ${climbingPlan.length?'with-plan':''}`}><PlanList items={climbingPlan}/><Note label="Лазание — что получилось" value={draft.climbing} onChange={climbing=>patch({climbing})} placeholder="Трассы, попытки, движения, техника, ощущения…" rows={7}/></div><div className={`entry-split ${strengthPlan.length?'with-plan':''}`}><PlanList items={strengthPlan}/><Note label="ОФП и висы — что сделал" value={draft.conditioning} onChange={conditioning=>patch({conditioning})} placeholder="Упражнения, подходы, нагрузка, заметки…" rows={6}/></div></div>
      </section>
      <section className="panel"><PanelTitle number="03" title="После тренировки"/><div className="field-grid"><NumberField label="Длительность, минуты" value={draft.duration} options={durationOptions} onChange={duration=>patch({duration},true)}/><NumberField label="RPE — субъективная тяжесть занятия (0–10)" value={draft.rpe} options={ratingOptions} onChange={rpe=>patch({rpe},true)}/><NumberField label="Левая кисть — дискомфорт во время (0–10)" value={draft.leftWrist} options={ratingOptions} onChange={leftWrist=>patch({leftWrist},true)}/></div><p className="field-help">RPE: 0 — отдых, 10 — предельно тяжёлая тренировка.</p></section>
      <section className="panel"><PanelTitle number="04" title="Следующее утро"/><p className="muted">Можно заполнить позже. Пусто — не записано; 0 — дискомфорта нет.</p><div className="field-grid"><NumberField label="Левая кисть (0–10)" value={draft.morning.wrist} options={ratingOptions} onChange={wrist=>patch({morning:{...current.current.morning,wrist}},true)}/><NumberField label="Пальцы (0–10)" value={draft.morning.fingers} options={ratingOptions} onChange={fingers=>patch({morning:{...current.current.morning,fingers}},true)}/><NumberField label="Разбитость (0–10)" value={draft.morning.fatigue} options={ratingOptions} onChange={fatigue=>patch({morning:{...current.current.morning,fatigue}},true)}/></div><Note label="Заметка утром" value={draft.morning.note} onChange={note=>patch({morning:{...current.current.morning,note}})} rows={3}/></section>
      {stored&&<button className="delete-button" onClick={()=>void remove()}>Удалить запись за день</button>}
    </div></div>
  </main>;
}

function ProgramPage({program,onLoaded}:{program:ProgramPackage|null;onLoaded:()=>void}){
  const input=useRef<HTMLInputElement>(null),[query,setQuery]=useState(''),[message,setMessage]=useState('');
  async function loadFile(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];event.target.value='';if(!file)return;try{await importProgram(JSON.parse(await file.text()));setMessage('Программа сохранена на устройстве.');onLoaded()}catch(cause){setMessage(cause instanceof Error?cause.message:String(cause))}}
  const q=query.trim().toLocaleLowerCase('ru'),sections=program?.sections.filter(section=>!q||`${section.title} ${section.text}`.toLocaleLowerCase('ru').includes(q)||program.exercises.some(exercise=>exercise.section===section.id&&`${exercise.title} ${exercise.dose} ${exercise.instruction}`.toLocaleLowerCase('ru').includes(q)))||[];
  const templateLink=<a className="secondary-link" href={`${import.meta.env.BASE_URL}program-template.json`} download="program-template.json">Скачать пустой шаблон JSON</a>;
  return <main className="content program-page"><div className="page-intro"><span className="eyebrow">ПЛАН ПОД РУКОЙ</span><h1>Программа</h1><p>Справочник упражнений и этапов. Загрузка программы не создаёт занятия в календаре автоматически.</p></div>
    <input ref={input} type="file" accept=".json,application/json" hidden onChange={event=>void loadFile(event)}/>
    {!program?<section className="panel program-import"><div className="empty-mark">◇</div><h2>Загрузи программу</h2><p>Выбери готовый файл программы или скачай пустой шаблон и заполни его. Файл сохранится только в этой PWA.</p><button className="primary" onClick={()=>input.current?.click()}>Импортировать программу</button>{templateLink}</section>:<><section className="panel program-head"><div><span className="eyebrow">ЗАГРУЖЕНА · {program.version}</span><h2>{program.title}</h2></div><button className="secondary" onClick={()=>input.current?.click()}>Обновить файл</button></section>{!!program.startRules?.length&&<details className="panel program-extra start-rules"><summary>Правила начала и остановки · {program.startRules.length}</summary><div className="source-list">{program.startRules.map((rule,index)=><p key={index}><b>{rule.label}</b><br/>{rule.text}</p>)}</div></details>}<label className="field search-field"><span>Поиск по тексту и упражнениям</span><input type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Например, пальцы или отдых"/></label><div className="program-sections">{sections.map((section,index)=><details className="panel program-section" key={section.id} open={!!q}><summary><span>{String(index+1).padStart(2,'0')}</span><strong>{section.title}</strong></summary><div className="program-text">{section.text}</div></details>)}{q&&sections.length===0&&<p className="muted">По запросу ничего не найдено.</p>}</div><details className="panel program-extra"><summary>Упражнения и дозировки</summary><div className="exercise-library">{program.exercises.filter(exercise=>!q||`${exercise.title} ${exercise.dose} ${exercise.instruction}`.toLocaleLowerCase('ru').includes(q)).map(exercise=><div key={exercise.id}><b>{exercise.mode} · {exercise.title}</b><p>{exercise.dose}</p><small>{exercise.instruction}</small></div>)}</div></details><details className="panel program-extra"><summary>Пример последовательности · {program.weeks.length} недель</summary><div className="week-list">{program.weeks.map(week=><div key={week.start}><b>{formatDate(week.start)} — {formatDate(week.end)}</b><strong>{week.phase}</strong><p>{week.note}</p></div>)}</div></details><details className="panel program-extra"><summary>Источники · {program.sources.length}</summary><div className="source-list">{program.sources.map(source=><p key={source.id}><b>{source.name}</b><br/>{source.note}<br/><a href={source.url} target="_blank" rel="noopener noreferrer">Открыть источник ↗</a></p>)}</div></details><details className="panel program-extra template-bottom"><summary>Формат файла программы и пустой шаблон</summary><p>Шаблон содержит поля разделов, упражнений и тренировок. Персональная программа не входит в публичный сайт.</p>{templateLink}</details></>}
    {message&&<div className="notice" role="status">{message}</div>}
  </main>;
}

function StorageDialog({onClose,onRestored}:{onClose:()=>void;onRestored:()=>void}){
  const fileInput=useRef<HTMLInputElement>(null),[lastExport,setLastExport]=useState<string|null>(null),[message,setMessage]=useState(''),[preview,setPreview]=useState<Backup|null>(null),[busy,setBusy]=useState(false);
  useEffect(()=>{void getSettings().then(settings=>setLastExport(settings.lastExportAt))},[]);
  async function exportNow(){setBusy(true);try{const result=await shareBackup(await makeBackup());if(result!=='cancelled'){await markExport();setLastExport((await getSettings()).lastExportAt);setMessage(result==='shared'?'Файл передан в системное меню. Проверь, что он сохранён в «Файлы».':'Файл скачан. Проверь место сохранения.')}}catch(cause){setMessage(cause instanceof Error?cause.message:String(cause))}finally{setBusy(false)}}
  async function readFile(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];event.target.value='';if(!file)return;try{setPreview(parseBackup(await file.text()));setMessage('')}catch(cause){setPreview(null);setMessage(cause instanceof Error?cause.message:String(cause))}}
  async function restore(){if(!preview||!confirm('Полностью заменить данные на этом устройстве выбранной копией? Сначала можно экспортировать текущие записи.'))return;setBusy(true);try{await restoreBackup(preview);setPreview(null);setMessage('Данные восстановлены.');onRestored()}catch(cause){setMessage(cause instanceof Error?cause.message:String(cause))}finally{setBusy(false)}}
  const dates=preview?.days.map(day=>day.date).sort()||[];
  return <div className="modal-backdrop" onClick={onClose}><section className="settings-dialog" role="dialog" aria-modal="true" aria-label="Данные и резервная копия" onClick={event=>event.stopPropagation()}><div className="dialog-head"><div><span className="eyebrow">НА ТВОЁМ УСТРОЙСТВЕ</span><h2>Данные и копия</h2></div><button className="icon-button" aria-label="Закрыть" onClick={onClose}>×</button></div><p>Записи автоматически сохраняются внутри установленной PWA и открываются без сети. Сайт не отправляет их на сервер.</p><div className="settings-block"><h3>Резервная копия</h3><p>В iCloud Drive попадёт только файл, который ты сам сохранишь через «Файлы». Это копия, а не живая синхронизация дневника.</p><p className="muted">Последний экспорт: {lastExport?new Date(lastExport).toLocaleString('ru-RU'):'ещё не делали'}.</p><button className="primary full" disabled={busy} onClick={()=>void exportNow()}>Сохранить копию JSON</button><input ref={fileInput} type="file" accept=".json,application/json" hidden onChange={event=>void readFile(event)}/><button className="secondary full" disabled={busy} onClick={()=>fileInput.current?.click()}>Восстановить из файла</button>{preview&&<div className="restore-preview"><b>Файл проверен</b><p>{preview.days.length} дней · {preview.programs.length} программ · {preview.legacyWorkouts.length} старых подробных записей</p><p>{dates.length?`${formatDate(dates[0])} — ${formatDate(dates.at(-1)!)}`:'Даты отсутствуют'}</p><button className="delete-button full" onClick={()=>void restore()}>Заменить данные этой копией</button></div>}</div><p className="muted">Safari и иконка PWA на главном экране могут хранить разные записи. Начни вести дневник в установленной PWA и периодически сохраняй копию.</p>{message&&<div className="notice" role="status">{message}</div>}</section></div>;
}

export function App(){
  const [route,setRoute]=useState<Route>(readRoute),[month,setMonth]=useState(()=>{const route=readRoute();return localDate(route.page==='day'?route.date:today())}),[days,setDays]=useState<DayEntry[]>([]),[program,setProgram]=useState<ProgramPackage|null>(null),[ready,setReady]=useState(false),[settingsOpen,setSettingsOpen]=useState(false),[notice,setNotice]=useState(''),[offlineReady,setOfflineReady]=useState(false),[updateReady,setUpdateReady]=useState(false);
  const updateServiceWorker=useRef<((reloadPage?:boolean)=>Promise<void>)|null>(null);
  async function reload(){try{const [loadedDays,loadedProgram]=await Promise.all([getDays(),getProgram()]);setDays(loadedDays);setProgram(loadedProgram);setReady(true)}catch(cause){setNotice(cause instanceof Error?cause.message:String(cause))}}
  useEffect(()=>{void reload();if(navigator.storage?.persist)void navigator.storage.persist().catch(()=>{});if('serviceWorker' in navigator)void navigator.serviceWorker.ready.then(registration=>{if(registration.active)setOfflineReady(true)}).catch(()=>{});updateServiceWorker.current=registerSW({onOfflineReady(){setOfflineReady(true)},onNeedRefresh(){setUpdateReady(true)}});const changed=()=>{setRoute(readRoute());window.scrollTo(0,0)};window.addEventListener('hashchange',changed);return()=>window.removeEventListener('hashchange',changed)},[]);
  const selected=route.page==='day'?days.find(day=>day.date===route.date):undefined;
  return <div className="app-shell"><header className="topbar"><div className="brand"><span className="brand-mark"><img src={`${import.meta.env.BASE_URL}icons/rock.svg`} alt=""/></span><span>КАМЕНЬ<small>ТРЕКЕР ТРЕНИРОВОК</small></span></div><div className="top-actions">{offlineReady&&<span className="offline-label">● Офлайн готов</span>}{route.page!=='day'&&<button className="settings-button" aria-label="Данные и резервная копия" onClick={()=>setSettingsOpen(true)}>⚙</button>}</div></header>{notice&&<div className="error-box global-error">{notice}<button onClick={()=>setNotice('')}>×</button></div>}{updateReady&&route.page!=='day'&&<div className="update-banner">Доступно обновление приложения. <button onClick={()=>void updateServiceWorker.current?.(true)}>Обновить</button></div>}
    {!ready?<main className="content"><p>Загружаю записи…</p></main>:route.page==='day'?<DayPage key={route.date} date={route.date} stored={selected} program={program} onBack={()=>go({page:'calendar'})} onProgram={()=>go({page:'program'})} onSaved={saved=>setDays(current=>current.some(day=>day.date===saved.date)?current.map(day=>day.date===saved.date?saved:day):[...current,saved])} onDeleted={date=>{setDays(current=>current.filter(day=>day.date!==date));go({page:'calendar'})}}/>:route.page==='program'?<ProgramPage program={program} onLoaded={()=>void reload()}/>:<Calendar days={days} month={month} onMonthChange={setMonth} onOpen={date=>go({page:'day',date})}/>}
    {route.page!=='day'&&<nav className="bottom-nav" aria-label="Разделы"><button className={route.page==='calendar'?'active':''} onClick={()=>go({page:'calendar'})}><span>▦</span>Календарь</button><button className={route.page==='program'?'active':''} onClick={()=>go({page:'program'})}><span>◇</span>Программа</button></nav>}{settingsOpen&&<StorageDialog onClose={()=>setSettingsOpen(false)} onRestored={()=>void reload()}/>}</div>;
}

createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
